---
- name: set mysql repository
  shell: rpm -Uvh --force http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm

- name: yum install mysql5.6
  yum: name={{item}} state=present
  with_items:
    - mysql-community-client-5.6.23-2.el6

- name: allow port 3306
  lineinfile: dest=/etc/sysconfig/iptables line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 3306 -j ACCEPT" insertafter="^:OUTPUT "
